### ISSUE TITLE
Add ambulance count on Hospital Info page in ER view.

### ISSUE THREAD

**Issue by joekaylor** [sfbrigade/bats-server#103]
<img width="344" alt="Screen Shot 2021-12-01 at 7 00 16 PM" src="https://user-images.githubusercontent.com/140766/144349859-d775b0fc-bf88-4156-9331-37668bdaaf76.png">

**Comment by francisli** [comment]
This has been partially implemented as part of #102, but could not be tested until the incoming ringdowns design change is implemented first- this is because, right now, any incoming ringdown takes over the full screen...

**Comment by francisli** [comment]
This is waiting on #113

**Comment by francisli** [comment]
This was partially implemented in #102 , and needs to be finished/tested...

The number of "incoming ringdowns" should reflect the number of ringdowns that are enroute/waiting (not offloaded) for the hospital
