### ISSUE TITLE
Deploy the app to Heroku or other live environment

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#14]
Also, set up Continuous Deployment from master branch.

**Comment by komerela** [comment]
I have been looking at deployment and was wondering whether working with express server is a preference before we begin deployment?

**Comment by francisli** [comment]
@komerela well, it's what we discussed earlier on in the project and is still pretty well used and de-facto standard for JS servers, to keep everything in JS so that it's accessible for both the front-end and back-end developers... what would be your suggested alternative?

**Comment by komerela** [comment]
@francisli I'm truly enjoying working with express.js. Apologies to have asked about this but before all the tech I heard was mostly foreign until I began working with it during the building of this project.

**Comment by francisli** [comment]
@komerela if you haven't done it already, the first thing to do is sign up for a free Heroku account and install the Heroku CLI, and log in to your account in the Heroku CLI: https://devcenter.heroku.com/articles/heroku-cli

Then, the `heroku create` command using the CLI can be used to create a new free deployment, and then a free postgres database can be added on: https://elements.heroku.com/addons/heroku-postgresql

Running the `heroku create` command from the project repository folder will add a new git remote to Heroku. So it's then just a `git push heroku master` to transfer the latest code on master branch to heroku and trigger a deploy.

If you want to create a branch to work on deployment configuration, and deploy a branch, then it's `git push heroku <branch name>:master`, that is, you're pushing your <branch name> branch in your local repo to the master branch of the heroku git remote.

You'll then see the output from Heroku setting up the deployment- it's likely to fail the first time due to configuration setup issues, but I think most Node project server config settings are specified in the package.json file: https://devcenter.heroku.com/categories/nodejs-support

Or by setting any needed environment config variables for the deployment: https://devcenter.heroku.com/articles/config-vars

It's a bit of a trial-and-error process to start, but once it's going it's then a fully managed and automated environment (that you can fork/clone/etc) that pretty much eliminates most sysadmin duties for maintaining a live deployment...

In fact, once all the kinks of deployment is worked out, you can then even just add an additional json file that describes the deployment environment such that anyone can immediately create and deploy the project in one click of a button:

https://devcenter.heroku.com/articles/heroku-button

**Comment by komerela** [comment]
@francisli  I'll be working on this and thanks for the info.

**Comment by francisli** [comment]
@komerela @julianmclain 

I've gone ahead and made an initial deployment in Heroku... didn't require much tweaking at all, just specifying the specific Node.js version in our package.json file. Site is live now at:

https://bats-dev.herokuapp.com/

Note you may need to wait some seconds (and maybe refresh) if the free server is asleep and needs to be launched. Here's a test user:

email: test@demo.com
password: Abcd1234!

If you let me know the email addresses for your Heroku accounts, I'll add you to the deployment so you can inspect it and push code for deploys...
