### ISSUE TITLE
EMS: Update EMS Form:

### ISSUE THREAD

**Issue by joekaylor** [sfbrigade/bats-server#169]
- Grey out Code 3 as option
- updated header
- Replaced 'IV Started' w/ 'Treatment administered. When checked, text field opens
- Added GCS score

See figma: https://www.figma.com/file/5FQp0yeFrJOCR4DapnLUG3/RoutED---Ambulance-Destination-Tool?node-id=0%3A1

**Comment by fwextensions** [comment]
A fix for this is waiting on PR #185.  Once that's reviewed and merged, a PR for this can be opened.

Tried floating the *optional* label to the right.  Made the heart and respiratory rate labels have a parallel format.

![image](https://user-images.githubusercontent.com/61631/180588122-0b514e51-d67d-476f-aef8-30515f6a548c.png)

Added *Treatments Administered* at the top of the last section.  Added GCS field.

![image](https://user-images.githubusercontent.com/61631/180588200-c2c1b65e-a2c3-4eb2-b6f9-cc37ffb2b72b.png)

**Comment by joekaylor** [comment]
**need to ask Callum
