### ISSUE TITLE
Create seed scripts for an initial data set

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#17]
Populate initial list of:

Hospitals
EMS Agencies

**Comment by billhoke** [comment]
Created Google sheet, "[Reference and Master Data Seeder](https://drive.google.com/drive/folders/1Qa1ZUsrUoW8ulJxYa-Fkzak9KGAh6wY4)", for defining values and deriving SQL (insert) statements. Initial values populated, but review and completion with Lissa remains.
