### ISSUE TITLE
EMS: Update header and tabs

### ISSUE THREAD

**Issue by joekaylor** [sfbrigade/bats-server#170]
See figma:
https://www.figma.com/file/5FQp0yeFrJOCR4DapnLUG3/RoutED---Ambulance-Destination-Tool?node-id=0%3A1

**update the header to V1.2 style

**Comment by fwextensions** [comment]
@joekaylor what needs to change here?  Just slight differences in *Behav. beds* and *Amb. offloading* headers?

**Comment by joekaylor** [comment]
**update style for the header
