### ISSUE TITLE
EMS: Updated Hospital Selection

### ISSUE THREAD

**Issue by joekaylor** [sfbrigade/bats-server#171]
- added ETA 

See figma: https://www.figma.com/file/5FQp0yeFrJOCR4DapnLUG3/RoutED---Ambulance-Destination-Tool?node-id=3948%3A61071

**Comment by francisli** [comment]
Re-opening, as I assume this issue is referring to the larger redesign, and not just the missing red required asterisks.

**Comment by fwextensions** [comment]
What's the larger redesign?

**Comment by francisli** [comment]
Well, I see this in Figma now, which has more changes to the type, spacing, and more separator lines?

<img width="384" alt="Screen Shot 2022-08-09 at 5 06 28 PM" src="https://user-images.githubusercontent.com/140766/183782527-1045ebb9-2149-4581-a0a8-040fb97ab296.png">

**Comment by fwextensions** [comment]
I see a couple tweaks to the radio labels are needed.  Also, not really sure how that list is organized.  Not alphabetically, certainly.

The spacing in the Figma file isn't consistent with where the app is currently, which Callum is okay with.

The divider over ETA seems like a mistake.  On the main ringdown form, only titled sections have dividers, not individual fields.

**Comment by fwextensions** [comment]
Re: the hospital names, it looks like those need to be changed in the database, which I'm not sure how to do.  I guess via a migration step?
