### ISSUE TITLE
User/Role/Organization data modeling

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#19]
How do we scope User access to different sections, etc...?

**Comment by billhoke** [comment]
Now that we have a pathway to SFFD paramedics' userids, shall we assume that:
- SFFD paramedics will log into the app. (Previously, we'd heard that they don't even log in to the laptops; rather, they just grab it and go.)
- all paramedics (even non-SFFD) will be setup as users and that we can associate them with a session (and each ring down)?

@julianmclain and @francisli - love to hear your thoughts on that.

For hospital admins ... I think I'd like to sketch out an alternative (TBD).

**Comment by francisli** [comment]
I think the answer is YES on both points, we will start from the assumption that everyone interacting with the system will have their own user account that they must log in to and have an authenticated session from which we can associate them with records in the database.

This might be a time in which we consider redesigning the "source" columns from an arbitrary text string to a user foreign key reference?

**Comment by billhoke** [comment]
I started a conceptual model just to get my head around the various organization types and their potential roles, and I'm trying to avoid the most complex representations (have you heard of "The Party Model"?). One thing that is convenient is that we seem to have only three role types: operational user (paramedic or ED admin), administrative user (for user maintenance and/or reporting) and the superuser. Does that sound right? Would either of you (@francisli, @julianmclain) be up for a discussion this weekend or early next week to work on the design?

**Comment by julianmclain** [comment]
Hey @billhoke - I think the three roles you outlined make sense. Within operational users, what are your thoughts on how to represent the paramedic vs. the ED admin? Also, I'm 100% onboard with avoiding anything too complicated for now.

We could spend time chatting about this before or after our standing Wednesday meeting. What do you think @francisli and @billhoke?

**Comment by francisli** [comment]
I think the three role types sounds right- I'm all for avoiding unnecessary complexity. I'm happy to jump on a short call one of these evenings, let me know otherwise we can chat on Weds per Julian's suggestion...

**Comment by billhoke** [comment]
@francisli and @julianmclain I'm open tomorrow, Tuesday or Wednesday (before the meeting). I did some more work on it and wrote out my notes, created an alternative logical data model, and put them both up [on Google Drive](https://drive.google.com/drive/folders/1Qa1ZUsrUoW8ulJxYa-Fkzak9KGAh6wY4?usp=sharing) for your review. If you don't get to it before we meet - no worries - we can just discuss then. Thanks! Bill

**Comment by julianmclain** [comment]
@billhoke This week I can only meet on Wednesday, but don't let me slow  down progress!

**Comment by billhoke** [comment]
@julianmclain and @francisli would you be available before the meeting tomorrow? Would 6pm work?

**Comment by francisli** [comment]
@billhoke @julianmclain 6pm tomorrow works for me, do you think we'll need an entire hour?

**Comment by julianmclain** [comment]
@billhoke @francisli I'm free tomorrow between 6 - 7pm for however much time we need.

**Comment by billhoke** [comment]
@francisli and @julianmclain let's meet at 6:30 to conserve time per your comment, Francis. If we need more time we can figure that out at that point. Thank you both for making the time.

**Comment by julianmclain** [comment]
@francisli @billhoke that works for me - chat soon!

**Comment by francisli** [comment]
Sounds good, let's just start the call in the main project slack channel so anyone can join and we can just transition right into the weekly standup call as folks trickle in...

**Comment by billhoke** [comment]
Updated models and DDL are on [Bill's Google drive](https://drive.google.com/drive/folders/1Qa1ZUsrUoW8ulJxYa-Fkzak9KGAh6wY4).
