### ISSUE TITLE
Update Heroku build process to use the latest stack

### ISSUE THREAD

**Issue by fwextensions** [sfbrigade/bats-server#198]
A notification from Heroku:

> Your recently built app [bats-dev](https://dashboard.heroku.com/apps/bats-dev/activity) is using the Heroku-18 stack, which is deprecated.
From February 1st, 2023, the first build of each Heroku-18 app within a 7-day period will fail with a deprecation notice.
From April 1st, 2023, the frequency of these failures will increase to the first build of each app per day.
On April 30th, 2023, Heroku-18 reaches end-of-life; apps using it will no longer receive security updates, and be run at your own risk.
From May 1st, 2023, builds will no longer be allowed for Heroku-18 apps.
Please [upgrade to a newer stack](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack) as soon as possible.
See the [Heroku-18 End-Of-Life FAQ](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq) for more details.

**Comment by francisli** [comment]
I'm not sure when this notification was issued, but back on July 18, I re-deployed all the apps in the pipeline (bats-dev, bats-stage, bats-prod), and they are now up to Heroku-22.

**Comment by fwextensions** [comment]
Saw it in Slack and just wanted to make sure it was tracked.
