### ISSUE TITLE
EMS: When patient is offloaded, ringdown summary shouldn't show Dismiss in the EMS view

### ISSUE THREAD

**Issue by fwextensions** [sfbrigade/bats-server#225]
In the EMS view, what would it mean for the EMT to dismiss a ringdown?  This link should only be available to the charge nurse.

![image](https://user-images.githubusercontent.com/61631/188008187-b93161ed-d1a9-41d6-93ed-5e39766eb3ba.png)

**Comment by fwextensions** [comment]
Clicking Dismiss also triggers an exception: `TypeError: onStatusChange is not a function`.

**Comment by fwextensions** [comment]
Sorry, didn't realize this was already assigned.

**Comment by KotovSyndrome** [comment]
I'd still like to use this issue as a practice issue and for familiarization purposes, may I attempt to fix this and submit a PR?

**Comment by fwextensions** [comment]
Sure, no problem.  #230 is also open.
