### ISSUE TITLE
EMS: User is able to submit invalid values in form fields (resulting in a server error, not displayed)

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#247]
For example, number values not within min/max

**Comment by francisli** [comment]
To do:

- Add styles for HTML validation psudoselectors (i.e. :invalid)
- Check the HTML validation status of form inputs, enable/disable Select Hospital button appropriately
- Add a generic alert popup for when unexpected server errors occur
..?

**Comment by fwextensions** [comment]
Another example is the incident number.  If it includes a letter, no error is shown, but the ringdown won't submit.
