### ISSUE TITLE
EMS: numeric fields do not show 0 when it's entered

### ISSUE THREAD

**Issue by fwextensions** [sfbrigade/bats-server#248]
Entering a `0` counts as a filled field for the form but the field appears empty.  It's likely due to something checking for a truthy value instead of an empty string or `null`.

**Comment by ap247** [comment]
Are there particular fields for which 0 does not show? I tried to send a ringdown through EMS User with as many zeroes as I could and most if not all fields showed up when logged in as a Hospital user.
