### ISSUE TITLE
Update data models for latest changes

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#25]
https://drive.google.com/file/d/1TW2IYd3vwKdeWZa8oUJRdUMmh9rFfmYE/view?usp=sharing

https://drive.google.com/file/d/1ifquDlxcbRUz03C8SPC2KOq7c9Z04_Yk/view?usp=sharing

https://drive.google.com/file/d/10bkzpp6W3UHDMTRCtPGWO5EYTjRQOAA_/view?usp=sharing

**Comment by francisli** [comment]
@billhoke I'm looking at the latest changes and have some questions...

Do we really need tables for emergencyresponsetype and lowoxygenresponsetype or can we just create some ENUM types for these values?

emergencymedicalservicecall.startdatetime changed from a timestamp to a time without time zone type. Was that intentional?

Index/key naming conventions and formatting of the sql file have changed- I'm guessing it's because the Target DBMS setting has changed from PostgresQL 9.x to PostgresQL 10.x-12.x? Because of that change, I'm going to go ahead and implement these changes as a complete db schema drop and recreate so everything is in sync.

Eventually, though, I'd like to get to a point where we can make changes incrementally in the migrations (especially once we start having some data in the tables)... does the tool you're using have the ability to export such change migrations? Or will it be a developer making a diff of the sql files and coding it themselves? The latter is perfectly doable, but it will be easier once things are more stable and the diffs are smaller...

**Comment by francisli** [comment]
Change emergencyresponsetype and lowoxygenresponsetype from tables to ENUMs...

Change patientdelivery.deliverystatus to an ENUM... ringdown sent/received/arrived/offloaded/return to service. And rename/add timestamps to match.

**Comment by francisli** [comment]
Drop patient.patientnumber for now until we have a clear need/use for it.

**Comment by francisli** [comment]
Business timestamps to be stored in LOCAL time, add a unique suffix to identify those columns

emergencymedicalservicecall.startdatetimelocal
hospitalstatusupdate.updatedatetimelocal
...

And add a timezone setting column to organization. And we can also just have this set in local time on the client, sent to the server, stored verbatim.

**Comment by francisli** [comment]
emergencymedicalservicecall.startdatetimelocal goes back to being a timestamp

**Comment by francisli** [comment]
@julianmclain @komerela the above comments I think cover everything we talked with @billhoke in the followup call regarding the latest data model changes...

**Comment by komerela** [comment]
Thank you @francisli I really appreciate the update, I'll take a look tomorrow & if there are any questions I'll reach out.

**Comment by julianmclain** [comment]
@billhoke @francisli On the `hospitalstatusupdate` table, I think we should consider making the `openedbedcount` and `openpsychbedcount` fields mandatory.

To power the EMS UI, I imagined that our app would query the database for the most recent hospitalstatsupdate record per hospital. That's not going to work if the most recent record doesn't contain all the relevant info. When an ED admin wants to update a single point of data (like `openedbedcount`), I'm thinking that the frontend will include even the fields that didn't change in the request to the backend.

Let me know if you have another thought on how displaying the current status per hospital could work.

**Comment by billhoke** [comment]
@francisli and @julianmclain : the changes are on my Google Drive. Change notes are:

Changes in 10/22 version:
- General change to all business datetime columns: 
  - datatype: timestamp without time zone 
  - naming suffix: "...datetimelocal"
- Patient:
  - Changed two look-ups (added 10/19) to ENUMs:
    - emergencyserviceresponsetypeenum
    - lowoxygenresponsetypeenum
  - Dropped patientnumber (we don't see a use for this)
- HospitalStatusUpdate:
  - Changed bed count columns to NOT NULL
- Patient Delivery
  - Renamed all status datetime columns to match UI terms  
  - Added Back to Service timestamp
     - Heads up: value related to the call, not one patient
  - Changed delivery status to ...ENUM
      - sent/received/arrived/offloaded/return to service
- Organization
  - Changed organizationtypename to ...ENUM
  - Added timezoneisocode with default to 'PST'
- Alter statements added for special datatypes

**Comment by billhoke** [comment]
@francisli and @julianmclain one more thought: I sometimes wish we had a separate table for patient delivery events so that we didn't have the many status-specific date columns, and so that any changes in the workflow by SFFD would not require column changes and would not in any way mess up the structure of historical rows. If you ever want to discuss that more, I'm open. Of course it would be yet more change, so I totally understand if your cup runneth over enough already. ;-)

**Comment by francisli** [comment]
@billhoke I see what you're saying about all the timestamp columns... but let's go with it for now and we can decide to make that change later if it ends up being a hassle...

One thing I just saw doing a diff of the new 10-23.sql vs 10-19.sql file:

In the users table, the email column reverted back from citext to varchar, and the ssodata column changed from jsonb to json. I think we'd prefer to have the citext and jsonb types for those columns...

**Comment by francisli** [comment]
@julianmclain in the code I see a comment about turning the patient sex column into an enum as well. Thoughts @billhoke ?

Also, one more thing that I've been modifying manually on the sql:

I'm setting the foreign key constraints on batsuser and organization to: DEFERRABLE INITIALLY DEFERRED

This is because, in the initial case of the bootstrap C4SF user, we have a circular reference between the user and the org. So deferring the constraint allows me to create those records one after the other and then update the first with the id of ther other.

**Comment by billhoke** [comment]
@francisli I'm putting all postgres features not supported by my data modeling tool in a part of the data model that runs right after the create statement, known as "post sql". That allows me to embed them in the model so that they reliably and automatically appear in the DDL without me having to manually edit (and forget or fat-finger) the script. The following statements are included after the CREATE statement for batsuser: 

- alter table batsuser alter column email type citext;
- alter table batsuser alter column ssodata type jsonb;

@julianmclain love the ideas - enum for sex (I'll work on that now) and the constraint work around for the chicken-and-egg problem. ;-) More to come...

**Comment by billhoke** [comment]
Okay applying a change to the existing SQL would look like this: 

alter table patient 
   rename column sex to sexenum;

CREATE TYPE sextype AS ENUM ('MALE', 'FEMALE', 'NON-BINARY');
alter table patient 
   alter column sexenum type sextype 
   using sexenum::sextype;

I'll re-generate the full set, too ...

**Comment by francisli** [comment]
@billhoke @julianmclain  a few more things I'm seeing missing from the patient model as I work on getting closer to connecting the frontend/backend:

- Although we have oxygensaturation (the percentage) and lowoxygenresponsetypenum (room air, supplemental) columns now, we don't have a column yet for the amount of supplemental oxygen (in liters)
- We don't have a column for the COVID-19 suspected checkbox (covid19suspectedindicator ?)

**Comment by francisli** [comment]
@billhoke @julianmclain a few MORE things ;) as I continue to work through the front end...

- I'd like the hospital selection list and hospital status tab to be dynamic- however, the design has the hospitals in a specific custom list order (NOT alphabetical/distance/time/etc). Can we add a simple integer ordering column to the hospital table so that we can seed the hospitals in this specific order?

- The Hospital Selection step also captures an Estimated Arrival time in minutes. We should have another integer column for that value as it was entered by the user into patientdelivery (which can then be used to compute the estimated arrival datetime by adding it to the ringdownsentdatetimelocal once the record has been committed).

**Comment by billhoke** [comment]
@francisli I'm going to try to carve out some time today to work on these.

**Comment by billhoke** [comment]
@francisli and @julianmclain sorry for the delayed response on this one. I made the above changes, and was prompted by the point about sort sequence to add some "active indicator" columns for tables that will eventually contain rows are no longer active/valid/etc. and therefore no longer available for drop-down lists and assignment to new instances in child tables. The revised DDL and diagram are up on the Google drive. 

Change Notes:

Patient
- Added supplementaloxygenamount
    Questions: Is this total, or liters/minute? 
      Should this be clear on the UI?
- Added covid-19suspectedindicator

Hospital
- Added sortsequencenumber
- Added activeindicator to disable closed hospitals

Bats User
- Added activeindicator to disable inactive users

Organization
- Added activeindicator to disable inactive hospitals or EMS organizations

Patient Delivery
- Added etaminutes

Question: how will ambulance data be used? The table facilitates a look-up or data validation. The UI control appears to be free text. Is this the right pair of designs? Do we need an "active indicator" for ambulances no longer in use?

**Comment by francisli** [comment]
@billhoke some feedback on the latest sql export:

Patient
- I think the hyphen in the covid-19 column name confused your tool- it was exported as "19suspectedindicator"

Patient Delivery
- I don't see an etaminutes column in the export

For the activeindicator, should we make that a NOT NULL column in all columns? Default TRUE?

**Comment by billhoke** [comment]
@francisli I made the changes you mentioned above. Upon review, I decided to add the Active Indicator to two other tables that will be used for filtering and selection: Hospital User and (maybe ... TBD) Ambulance. Changes are on my Google Drive. Thanks!
