### ISSUE TITLE
Site: update routedapp.org to Gatsby v5

### ISSUE THREAD

**Issue by fwextensions** [sfbrigade/bats-server#254]
I'm not really sure what's in v5, but the site is currently on v4.  https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/

This might be a good task for someone else to get up to speed on how the Routed site is put together.

**Comment by ap247** [comment]
https://github.com/routedapp/routedapp.github.io/pull/1

**Comment by ap247** [comment]
https://github.com/routedapp/routedapp.github.io/pull/1

**Comment by ap247** [comment]
https://github.com/routedapp/routedapp.github.io/commit/258a057be84f36cc35dfbaa77fb0048954a4ae2c
