### ISSUE TITLE
Admin can turn on two factor auth for an Organization

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#283]

**Comment by olupelumi** [comment]
I can take this on

**Comment by olupelumi** [comment]
Jus to clarify understanding, the admin here would be the `[batsadmin@c4sf.me]/abcd1234 (a Superuser)`?

**Comment by francisli** [comment]
Yes, that "superuser" account is the full site admin

**Comment by olupelumi** [comment]
Cool. So both superusers and admins should be able to toggle two-factor authorization for an organization. The superuser for any organization and the admin for their specific organization.
