### ISSUE TITLE
Write E2E tests for 2FA

### ISSUE THREAD

**Issue by ap247** [sfbrigade/bats-server#304]

**Comment by Code4Dopamine** [comment]
Source: https://stackoverflow.com/questions/68000771/run-grouped-tests-sequentially-using-playwright 
![image](https://github.com/sfbrigade/bats-server/assets/11954656/725ce181-f3cc-461a-9cca-0f1c78d059ec)

Seems like the method above allows Playwright to test "sequentially", which should avoid the race timing issue when testing 2FA via email.

**Comment by ddrosario** [comment]
Just to add the tests work after adding the following to `home.spec.js`
```javascript
test.describe('home', () => {
  test.describe.configure({ mode: 'serial' });
  test('shows the Routed logo and sign in form', async ({ page }) => {
    await page.goto('/');
```
and `twoFA.spec.js`
```javascript
test.describe('home', () => { // Must be run as last test so that last email contains correct authorization code
    test.describe.configure({ mode: 'serial' });
    test('logs in as EMS user with 2FA', async ({ context }) => {
        const appPage = await context.newPage();
```
