### ISSUE TITLE
Create first version of data model

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#4]
Based on @billhoke data model, create a migration for the database schema and the corresponding collection of models using the Sequelize ORM.

**Comment by komerela** [comment]
Thanks Francis, I'll take a look tomorrow.

**Comment by billhoke** [comment]
Here's another version of the DDL, fixing two mistakes on data types (noted in comments).

I'll try to get this stuff into Github in a separate folder ... soon ... bit busy at the moment.
