### ISSUE TITLE
EMS User will only see Ambulance Unit nos for their organization

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#71]
The ambulances API supports passing in an `organizationId` query parameter to filter the list for the given organization. We need to support that in the React SPA and pass that value from the user object to filter the ambulances list in the dropdown.

**Comment by francisli** [comment]
Let's also make sure to add an ordering to the results so the dropdown list doesn't look so random

**Comment by abmcbride5** [comment]
Ok. I'll work on this.
