### ISSUE TITLE
Crash editing Ringdown after Redirect

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#77]
Repo steps:

1. Log in as EMS user
2. Submit a new Ringdown to a Hospital
3. Confirm Redirect of the Ringdown
4. On the Hospital Selection page, click on Edit Ringdown
5. Expected: the Ringdown form appears with data editable
6. Observed: crash:

<img width="683" alt="Screen Shot 2021-08-04 at 6 38 37 PM" src="https://user-images.githubusercontent.com/140766/128277573-c4604a40-a9d5-4fff-84e9-379f87fc8479.png">

**Comment by abmcbride5** [comment]
Hey Francis, I am taking a look into this to see what I can figure out. I am open to help with this issue.
