### ISSUE TITLE
EMS User can Mark Arrived even if ER User has not yet confirmed the Ringdown

### ISSUE THREAD

**Issue by francisli** [sfbrigade/bats-server#99]
<img width="1119" alt="Screen Shot 2021-12-01 at 6 35 55 PM" src="https://user-images.githubusercontent.com/140766/144348176-4daac719-efc8-4025-9021-b8a7acbd9d8a.png">

**Comment by francisli** [comment]
@billhoke it looks like we'll need to make a data model change to the patientdeliveryupdate table to support this interaction... right now we have one deliverystatus that moves through a linear state machine: RINGDOWN_SENT (EMS user submits) > RINGDOWN_RECEIVED (ER user acknowledges) > ARRIVED (EMS user marks arrived) > OFFLOADED > etc...

However, now we want to separately track whether the ER user has acknowledged, and allow the EMS user to mark arrived regardless...

I'm thinking of adding another column to track ringdownstatus in addition to deliverystatus...

**Comment by francisli** [comment]
I'm waiting to hear from Callum/Emily on what the "Pending" ringdown status is supposed to mean...

**Comment by billhoke** [comment]
@francisli okay makes sense. Another alternative would be to add a classification attribute to patientdeliverystatus (patientdeliverystatustypeenum?) that identifies which state machine is being updated, and then treat them as two independent state machines. I guess there are some impact tradeoffs to consider, too, though, and you're certainly in a better position to understand those than me.

**Comment by francisli** [comment]
@billhoke I've just opened a PR that I think allows us to implement the desired behavior without two separate columns/state machines... it basically just allows the RINGDOWN_RECEIVED and a new RINGDOWN_CONFIRMED state to be saved even if the state machine has already progressed to ARRIVED. Since we store all the state updates separately, and return all these state updates as part of the ringdown, it makes it possible to inspect the ER (SENT/RECEVIED/CONFIRMED) state in the list of state updates, while the currentDeliveryStatus on the main patientDelivery record follows the EMS state (SENT/ARRIVED/OFFLOADED/...)...
